python3 main.py \
        -interclusteringtype sync \
        -intraclusteringtype sync \
        -modelname cnnfemnist \
        -datasetname femnist \
        -clientnum 100 \
        -dataheterogeneitytype onelabeldominant \
        -computationcapabilitymatric fixed\
        -systemheterogeneity alltimesame \
        -clustercommunicationtime 800 \
        -clusteringtype clusterbyrandomshuffle \
        -clusternum 10 \
        -clustersize 10 \
        -centralserverepoch 100 \
        -clusterepochtype fixed \
        -clusterepoch 2 \
        -localepochtype fixed \
        -localepoch 3